name: Azure cdn purge 360 images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/spots/360images/*" --profile-name "cdn" --name "pump" --resource-group "pump"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()

      - name: Dispatch pumptrack-map worfklow
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'lluisd',
              repo: 'pumptrack-map',
              workflow_id: 'main_pumptrack-map-app.yml',
              ref: 'main'
            })
